### ISSUE TITLE
Update Error "The filename or extension is too long"

### ISSUE THREAD

**Issue by zmarkley-reawire** [conda-forge/nodejs-feedstock#29]
Trying to upgrade from nodejs: 8.9.1-0 conda-forge --> 9.9.0-0 conda-forge

Receive the following error:
```
Downloading and Extracting Packages
nodejs 9.9.0: #############################################################################                         |  76%

FileNotFoundError(2, 'The filename or extension is too long')
```
# Debug info
```
DEBUG conda.gateways.disk.create:extract_tarball(133): extracting C:\Users\[username]\AppData\Local\Continuum\Anaconda3\pkgs\nodejs-9.9.0-0.tar.bz2
  to C:\Users\[username]\AppData\Local\Continuum\Anaconda3\pkgs\nodejs-9.9.0-0
DEBUG conda.core.package_cache_data:execute(600): FileNotFoundError(2, 'The filename or extension is too long')
NoneType: None
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGABRT
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGBREAK
Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 812, in __call__
    return func(*args, **kwargs)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 14, in execute

    install(args, parser, 'update')
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 278, in handle_txn

    unlink_link_transaction.download_and_extract()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 175, in download_and_extract
    self._pfe.execute()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 604, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: [WinError 206] The filename or extension is too long: 'C:\\Users\\[username]\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\nodejs-9.9.0-0\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib'
```

# Conda Info
```
     active environment : data_visulation
    active env location : C:\Users\[username]\AppData\Local\Continuum\Anaconda3\envs\data_visulation
            shell level : 2
       user config file : C:\Users\[username]\.condarc
 populated config files : C:\Users\[username]\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.4.final.0
       base environment : C:\Users\[username]\AppData\Local\Continuum\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\[username]\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\[username]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[username]\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\[username]\AppData\Local\conda\conda\envs
                          C:\Users\[username]\.conda\envs
               platform : win-32
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
This is ultimately a `conda` problem that has been filed as issue ( https://github.com/conda/conda/issues/7203 ). Please follow along and share info there. FWIW there is a [suggested workaround]( https://github.com/conda/conda/issues/7203#issuecomment-390506535 ) for this issue. Going to close to consolidate the discussion in that issue. Thanks for reporting and sharing details.
